version: '3.9'
services:
  database:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
